#debug配置是否调试模式，如果打包发布的话，需要设置为false。
#默认情况下，spring boot从控制台打印出来的日志级别有error，warn，info，如果你要打印debug级别的日志，可设置debug=true
debug: false
#server.port配置的是 Spring Boot 服务的端口
server:
  port: 130
spring:
  application:
    name: app-service
  servlet:
    multipart:
      max-file-size: 100MB #  设置单个文件最大内存 -1为不限制
      max-request-size: 1024MB # 设置所有文件最大内存 -1为不限制
  #consul 注册中心
  cloud:
    consul:
      host: 127.0.0.1   #ip
      port: 8500        #端口
      discovery:
        register: true
        hostname: 127.0.0.1   #注册服务地址
        service-name: ${spring.application.name}   #注册服务名称
        health-check-path: /actuator/health
        health-check-interval: 15s
        tags: urlprefix-/${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  #mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.162:3306/dhlk_tenant_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: 1111
    hikari:
      minimum-idle: 5 # 连接池中维护的最小空闲连接数
      maximum-pool-size: 15  # 配置最大池大小
      auto-commit: true # 配置从池返回的连接的默认自动提交行为。默认值为true
      idle-timeout: 30000 # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      pool-name: DatebookHikariCP # 连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      max-lifetime: 1800000 # 池中连接关闭后的最长生命周期（以毫秒为单位）
      connection-timeout: 10000 # 客户端等待连接池连接的最大毫秒数
      connection-test-query: SELECT 1
  aop:
    proxy-target-class: true
    auto: false

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.dhlk.entity.light
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
logging:
  config: classpath:logback-spring.xml
swagger: ##给swagger设置开关
  ebable: true
